apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-balanced-walleye
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "892575085764"
    kanikoFlags: --skip-unused-stages --snapshotMode=redo
    project: ci-cd-400822
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - key: dev
    owner: mchekole
    repository: jx3-cluster-repo
  - key: staging
  - key: production
  ingress:
    domain: ""
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: mchekole
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-balanced-walleye-279f07afb1cb
  - name: reports
    url: gs://reports-tf-jx-balanced-walleye-279f07afb1cb
  - name: repository
    url: gs://repository-tf-jx-balanced-walleye-279f07afb1cb
  terraformVault: true
  vault:
    bucket: vault-tf-jx-balanced-walleye-279f07afb1cb
    key: crypto-key-tf-jx-balanced-walleye-279f07afb1cb
    keyring: keyring-tf-jx-balanced-walleye-279f07afb1cb
    name: tf-jx-balanced-walleye
    serviceAccount: tf-jx-balanced-walleye-vt
  webhook: lighthouse
